"""Syllable counting support for generated haiku lines."""


class SyllableCounter:
    """Manage syllable counts for words used in haiku generation.

    This class provides:
        - A built-in syllable dictionary for common haiku words.
        - Interactive fallback prompting for unknown words.
        - Caching of user-provided syllable counts to avoid repeated prompts.
    """

    def __init__(self) -> None:
        """Initialise the syllable counter with a predefined dictionary.

        The dictionary includes syllable counts for a wide range of words
        commonly found in nature-themed and abstract haikus.
        """
        self._syllable_dict: dict[str, int] = {
            "last": 1,
            "first": 1,
            "tender": 2,
            "newest": 2,
            "fresh": 1,
            "young": 1,
            "gust": 1,
            "stillness": 2,
            "silence": 2,
            "serenity": 4,
            "calmness": 2,
            "tranquility": 4,
            "autumn": 2,
            "spring": 1,
            "springtime": 2,
            "march": 1,
            "april": 2,
            "may": 1,
            "red": 1,
            "green": 1,
            "greenish": 2,
            "khaki": 2,
            "emerald": 3,
            "jade": 1,
            "yellow": 2,
            "blue": 1,
            "azure": 2,
            "cobalt": 2,
            "skyblue": 2,
            "sapphire": 2,
            "brown": 1,
            "teal": 1,
            "navy": 2,
            "silver": 2,
            "light": 1,
            "grey": 1,
            "unite": 2,
            "separate": 3,
            "split": 1,
            "part": 1,
            "scatter": 2,
            "disperse": 2,
            "carpet": 2,
            "roof": 1,
            "ceiling": 2,
            "crown": 1,
            "canopy": 3,
            "covering": 3,
            "under": 2,
            "above": 2,
            "overhead": 3,
            "upstairs": 2,
            "atop": 2,
            "beyond": 2,
            "trees": 1,
            "flowers": 2,
            "grass": 1,
            "creatures": 2,
            "fauna": 2,
            "wildlife": 2,
            "final": 2,
            "of": 1,
            "the": 1,
            "ultimate": 3,
            "latest": 2,
            "finishing": 3,
            "closing": 2,
            "breeze": 1,
            "puff": 1,
            "breath": 1,
            "blast": 1,
            "flurry": 2,
            "fall": 1,
            "equinox": 3,
            "october": 3,
            "november": 3,
            "december": 3,
            "crimson": 2,
            "rust": 1,
            "ochre": 2,
            "reddish": 2,
            "magenta": 3,
            "tawny": 2,
            "gold": 1,
            "yellowish": 3,
            "pale": 1,
            "ashen": 2,
            "auburn": 2,
            "tan": 1,
            "brownish": 2,
            "bronze": 1,
            "swarthy": 2,
            "join": 1,
            "fuse": 1,
            "merge": 1,
            "blend": 1,
            "amalgamate": 4,
            "rug": 1,
            "mat": 1,
            "layer": 2,
            "blanket": 2,
            "spread": 1,
            "below": 2,
            "beneath": 2,
            "underneath": 3,
            "down": 1,
            "downunder": 3,
            "bushes": 2,
            "foliage": 3,
            "shrubs": 1,
            "plants": 1,
            "vegetation": 4,
            "brilliance": 2,
            "radiance": 3,
            "sunlight": 2,
            "splendour": 2,
            "ocean": 2,
            "deep": 1,
            "water": 2,
            "exclusively": 4,
            "utterly": 3,
            "solely": 2,
            "only": 2,
            "specially": 3,
            "just": 1,
            "uniquely": 3,
            "glitters": 2,
            "sparkles": 2,
            "gleams": 1,
            "shimmers": 2,
            "glistens": 2,
            "diverts": 2,
            "redirects": 3,
            "turns": 1,
            "in": 1,
            "for": 1,
            "me": 1,
            "my": 1,
            "ship": 1,
            "no": 1,
            "more": 1,
            "cats": 1,
            "felines": 2,
            "kittens": 2,
            "basking": 2,
            "lying": 2,
            "relaxing": 3,
            "idling": 2,
            "lit": 1,
            "hit": 1,
            "reach": 1,
            "late": 1,
            "afternoon": 1,
            "rays": 1,
            "sun": 1,
            "not": 1,
            "all": 1,
            "wall": 1,
            "sky": 1,
            "storm": 1,
            "cloud": 1,
            "clouds": 1,
            "leaves": 1,
            "blow": 1,
            "float": 1,
            "drift": 1,
            "moss": 1,
            "river": 2,
            "stream": 1,
            "whispers": 2,
            "echo": 2,
            "path": 1,
            "trail": 1,
            "branch": 1,
            "bark": 1,
            "dawn": 1,
            "dusk": 1,
            "twilight": 2,
            "horizon": 3,
            "glow": 1,
            "shade": 1,
            "peace": 1,
            "quiet": 2,
            "song": 1,
            "hum": 1,
            "tree": 1,
            "dew": 1,
            "still": 1,
            "longing": 2,
            "dance": 1,
            "fade": 1,
            "forest": 2,
            "petal": 2,
            "whisper": 2,
            "soft": 1,
            "air": 1,
            "space": 1,
            "dust": 1,
            "shimmer": 2,
            "moon": 1,
            "on": 1,
            "at": 1,
            "a": 1,
            "rain": 1,
            "dark": 1,
            "dream": 1,
            "flow": 1,
            "stone": 1,
            "silent": 2,
            "falling": 2,
            "glimmer": 2,
            "morning": 2,
            "evening": 3,
            "shadows": 2,
            "tranquil": 2,
            "fluttering": 3,
            "eternal": 3,
            "drifting": 2,
            "bloom": 1,
            "mist": 1,
            "leaf": 1,
            "peaceful": 2,
            "flicker": 2,
            "wind": 1,
        }

    def get_syllable_count(self, word: str) -> int:
        """Retrieve or prompt for the syllable count of a given word.

        If the syllable count is already cached, it is returned directly.
        Otherwise, the user is prompted to input a positive integer count,
        which is then cached for future lookups.

        Args:
            word: Word to get the syllable count for.

        Returns:
            Number of syllables in the word.

        """
        clean_word = word.lower().strip(".,;:?!\"'")

        if clean_word in self._syllable_dict:
            return self._syllable_dict[clean_word]

        while True:
            try:
                count = int(input(f"\nHow many syllables does '{clean_word}' have? ").strip())
                if count <= 0:
                    raise ValueError

                self._syllable_dict[clean_word] = count
                return count

            except ValueError:
                print("Invalid input. Please enter a positive integer.")
